


steps:

- uses: actions/checkout@v3.1


- name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
  # uses: QAInsights/PerfAction@f3959d0a69e7f23949add25d7e34a3ae167d6443
  uses: QAInsights/PerfAction@v3.1
  with:
    # jmeter test plan to execute
    test-plan-path: './AROMHA SMOKE TEST 1 USER.jmx'

    - name: Upload Results
  uses: actions/upload-artifact@v3.1
  with:
    name: jmeter-results
    path: result.jtl
